### ISSUE TITLE
Running and debugging through Xcode

### ISSUE THREAD

**Issue by ptrkstr** [swift-cloud/Vercel#31]
Hey @AndrewBarba, thank you for this fantastic package, I believe you are on the path to revolutionising serverless Swift!
I've followed your [youtube video](https://www.youtube.com/watch?v=zzBhcYbtArY) which was a great resource in getting started. I couldn't help notice that one of the great things about Vapor is being able to run and debug (i.e. triggering breakpoints as a request comes in) through Xcode. Do you see feasibility of this package/serverless to be able to do that?

P.S. I love the direction you're going in with swift.cloud, I'm a big advocate for it!

**Comment by AndrewBarba** [comment]
Yes this is actually supported already! But I added support after I made that video. Just run:

```
swift package --disable-sandbox vercel server
```

And that will start the proxy server locally and nothing else. Then you can just click "Run" in Xcode and you will get full breakpoint support and can easily stop and restart and Xcode without stopping the proxy server.

**Comment by ptrkstr** [comment]
Thanks @AndrewBarba! That's worked perfectly 🙏
