### ISSUE TITLE
Deployment command on the blog post missing a parameter

### ISSUE THREAD

**Issue by hartti** [swift-cloud/Vercel#5]
Not exactly an issue in this repo, but the blog post you refer to (https://swift.cloud/blog/deploy-server-side-swift-applications-on-vercel) possibly contains an incorrect terminal command for deploying the app to Vercel. I think 
```
swift package --disable-sandbox vercel
```
should be
```
swift package --disable-sandbox vercel --deploy
```
(at least that is the deploy command on the repo documentation.)

**Comment by AndrewBarba** [comment]
Thanks for reporting this. I just updated the blog post and actually changed the deploy command to:

```
swift package --disable-sandbox vercel deploy
```

However the old `--deploy` will continue to work
