### ISSUE TITLE
Manual: Local deployment after changes

### ISSUE THREAD

**Issue by hartti** [swift-cloud/Vercel#6]
Apologies if this is too basic issue, but after initial deployment locally. I have hard time getting the code changes to be visible on local deployment.

First: The server is kept running on the background even if I press ctrl-C and I have to kill that process manually.
Second: Even after killing the server if I run the local deployment command (below) again the old built version is started. How do get the new version complied and visible on the server?
```
swift package --disable-sandbox vercel dev
```

I am missing something, what is probably common knowledge, but it might be good to get a couple of more lines of help on the readme, so server-side swift / vercel beginners like me, would be able to get a little further.

**Comment by hartti** [comment]
Found out the reason for this. When I stop the server by pressing ctrl-C, the Swift App itself is left running on the background. I need to manually kill that process and then run the command above again to see the changes.

**Comment by AndrewBarba** [comment]
@hartti Thanks for reporting this. I'm trying to figure out why the background Tasks are not being canceled. I thought with attached tasks, when the parent is canceled all the child tasks would also be canceled. Something is going on with the way I'm spawning the child processes here: https://github.com/swift-cloud/Vercel/blob/main/Plugins/VercelPackager/VercelOutput.swift#L85

I'm going to keep debugging this, but I'm open to any ideas.

**Comment by AndrewBarba** [comment]
Okay I think this fixes it: https://github.com/swift-cloud/Vercel/commit/b0432fab8d29599df3af0aa34cec8c2f8c045b22

Do you want to test using `branch: "main"` and if it works I'll create a new release?

**Comment by AndrewBarba** [comment]
I did a bunch of testing and ended up releasing 1.7.1 anyway. If you are still seeing issues let me know and I'll do another release.

**Comment by hartti** [comment]
Thanks! I will run this a few times tomorrow. Thanks also for linking to the correct place in the sources!

**Comment by hartti** [comment]
Hmmm... Does not seem to make any difference on my machine...
Here is terminal contents when I just restart the dev instance
```
swift package --disable-sandbox vercel dev

-------------------------------------------------------------------------
Starting dev server: http://localhost:7676
-------------------------------------------------------------------------


/Users/hartti/.nvm/versions/node/v16.13.2/bin/node /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel/.build/checkouts/Vercel/Plugins/VercelPackager/Server/server.js


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift run --package-path /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel

  Http Server running: http://localhost:7676
  Building for debugging...
  Build complete! (0.31s)
^Cerror: plugin process ended by an uncaught signal: 2 <command: /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel/.build/plugins/VercelPackager/cache/VercelPackager>, <output:
'
-------------------------------------------------------------------------
Starting dev server: http://localhost:7676
-------------------------------------------------------------------------


/Users/hartti/.nvm/versions/node/v16.13.2/bin/node /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel/.build/checkouts/Vercel/Plugins/VercelPackager/Server/server.js


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift run --package-path /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel

  Http Server running: http://localhost:7676
  Building for debugging...
  Build complete! (0.31s)
'>
```

And here is the terminal contents, when I first kill the App (I use Activity Monitor for that) and then run the dev instance
```
swift package --disable-sandbox vercel dev

-------------------------------------------------------------------------
Starting dev server: http://localhost:7676
-------------------------------------------------------------------------


/Users/hartti/.nvm/versions/node/v16.13.2/bin/node /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel/.build/checkouts/Vercel/Plugins/VercelPackager/Server/server.js


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift run --package-path /Users/hartti/Documents/WebProgramming/ultivideostats-server-vercel

  Http Server running: http://localhost:7676
  Building for debugging...
  Build complete! (0.16s)
  2023-02-15T00:10:48-0800 info LocalLambdaServer : [AWSLambdaRuntimeCore] LocalLambdaServer started and listening on 127.0.0.1:7000, receiving events on /invoke
  2023-02-15T00:10:48-0800 info Lambda : [AWSLambdaRuntimeCore] lambda runtime starting with LambdaConfiguration
  General(logLevel: info))
  Lifecycle(id: 28955990477708, maxTimes: 0, stopSignal: TERM)
  RuntimeEngine(ip: 127.0.0.1, port: 7000, requestTimeout: nil
^C
```

Also note that if run the dev instance, press ctrl-C and refresh the browser (to access the service) the service is still running. If I then kill the App, the browser refresh creates "Internal Server Error" (node is still running). And if I kill also node, then server is unreachable(

**Comment by hartti** [comment]
Running Ventura 13.1 on MacBook Pro (M1 Pro)

**Comment by hartti** [comment]
Ran the package update, built app again and now it works! The App and node are both killed when ctrl-C is pressed. Thanks!
Closing this issue
