### ISSUE TITLE
Can't build on Mac

### ISSUE THREAD

**Issue by mergesort** [swift-cloud/Vercel#8]
Hey @AndrewBarba,

I'm not sure if this is an issue with my setup but I opened the project I was working on a few weeks ago and started encountering this error, `Actor-isolated property 'body' can not be mutated on a non-isolated actor instance` in two places. It could definitely be something I did but I figured it was worth an ask since I wanted to try out your new Upstash library.

<img width="1378" alt="Screenshot 2023-05-01 at 17 25 39" src="https://user-images.githubusercontent.com/716513/235542242-e0696f8e-b4bc-4e5a-8e4b-7ed5e6bcbea7.png">
<img width="1376" alt="Screenshot 2023-05-01 at 17 27 16" src="https://user-images.githubusercontent.com/716513/235542437-f35cedf9-e391-408c-91c0-86710e3f2a08.png">

Thank you so much, can't wait to play with it some more!

**Comment by AndrewBarba** [comment]
Hey @mergesort can I see your `Package.swift`? I fixed an issue related to this earlier today, you may just need to: File -> Packages -> Update latest

**Comment by mergesort** [comment]
```
let package = Package(
    name: "XYZ",
    platforms: [.macOS(.v12)],
    dependencies: [
        .package(url: "https://github.com/swift-cloud/Upstash", from: "1.0.1"),
        .package(url: "https://github.com/swift-cloud/Vercel", from: "1.10.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .executableTarget(
            name: "XYZ",
            dependencies: [
                .product(name: "Upstash", package: "Upstash"),
                .product(name: "Vercel", package: "Vercel"),
            ],
            path: "Sources"
        ),
    ]
)
```

**Comment by AndrewBarba** [comment]
And whats the swift-tools-version at top of file and Xcode version? It's def an issue with swift 5.8 that I had to account for. You should see these resolved versions if you update to the latest:

<img width="292" alt="Screenshot 2023-05-01 at 6 40 20 PM" src="https://user-images.githubusercontent.com/1316152/235543917-7ecde5b3-7a11-4332-b028-c31926ee6dc0.png">

**Comment by mergesort** [comment]
Ahh, it looks like when I hit `Update latest` again one of the dependencies updated. I'm not sure why it didn't update before but that seems to have fixed things! Sorry to bother you with fragile tooling, I'll make sure to look out for that next time. 😅
