### ISSUE TITLE
Is It Possible To Use FluentKit With Vercel?

### ISSUE THREAD

**Issue by mergesort** [swift-cloud/Vercel#9]
Hey @AndrewBarba, sorry to keep throwing ideas at you but the more I use this the more I love it and see a ton of possibilities for my smaller projects and one-off ideas. I've been playing with [Neon](https://neon.tech) for a little side project, and thought it would be really neat to hook up a serverless function that pulls from a serverless database for some very low-maintenance infrastructure.

I was wondering if it was possible to use [FluentKit](https://github.com/vapor/fluent-kit) to connect to/read/write from a Postgres database, all in the span of a request. I could import Vapor and have this work, but I asked in the Vapor Discord and they said that it should be relatively easy to map the Fluent code to Vercel types.

To directly quote them
> You can certainly use FluentKit without Vapor (fluent itself has a hard dependency on Vapor but is simply the bridge between FluentKit and Vapor, it doesn't actually do much)
>
> Assuming Vercel has an event loop group and logger etc, you just ™️ need to set up a connection pool and basically do what Fluent does with the Vercel types

I could be off base and maybe the best answer is to use Vapor, but I wanted to check and see what you thought the best approach is.

Thank you again for all of these libraries and all of this functionality, I can't emphasize how cool I think what you're doing for the Swift community is.

**Comment by AndrewBarba** [comment]
First let me just say I _love_ how much feedback you've been giving. I think one of the hardest parts about developing open-source work in the Swift community is it's hard to get your project seen and used by people. So it's super refreshing to see you using it.

I'll do some investigating on how you can use FluentKit specifically, looks like you definitely can. Main issue is I can't find _any_ docs on FluentKit, maybe I'm looking in the wrong place? There's Fluent and FluentKit and I have no idea what differences are.

You can definitely use [postgres-nio](https://github.com/vapor/postgres-nio) directly though. I'll work on a starter kit that uses this until I can figure out how FluentKit works.

**Comment by AndrewBarba** [comment]
Here is working example with postgres-nio:

```swift
import Vercel
import PostgresNIO

let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)

let pg = try! PostgresConnection.connect(
    on: eventLoopGroup.next(),
    configuration: .init(
        host: Vercel.Environment["POSTGRES_HOST"]!,
        port: 5432,
        username: Vercel.Environment["POSTGRES_USER"]!,
        password: Vercel.Environment["POSTGRES_PASSWORD"]!,
        database: Vercel.Environment["POSTGRES_DATABASE"]!,
        tls: .require(.init(configuration: .makeClientConfiguration()))
    ),
    id: 1,
    logger: .init(label: "postgres-logger")
)

@main
struct App: ExpressHandler {

    static let router = Router()
        .get("/") { req, res in
            let conn = try await pg.get()
            return res.status(.ok).send("Hello, PG \(!conn.isClosed)")
        }
}
```

**Comment by mergesort** [comment]
>First let me just say I love how much feedback you've been giving. I think one of the hardest parts about developing open-source work in the Swift community is it's hard to get your project seen and used by people. So it's super refreshing to see you using it.

Thank you, I'm glad to give it! I know in my own personal projects I've often felt a bit overwhelmed with feedback so I didn't want to do the same to you, but I also suspect it's harder to get feedback for something server-related in the Swift community than something like a persistence layer which all iOS/macOS developers may be interested in.

---

> I'll do some investigating on how you can use FluentKit specifically, looks like you definitely can. Main issue is I can't find any docs on FluentKit, maybe I'm looking in the wrong place? There's Fluent and FluentKit and I have no idea what differences are.

When I asked earlier today about using Fluent in a non-Vapor setup like Swift.cloud I got this response from one of the core Vapor developers.

> You can certainly use FluentKit without Vapor (Fluent itself has a hard dependency on Vapor but is simply the bridge between FluentKit and Vapor, it doesn't actually do much).

I took that to mean that the docs you find for Fluent are as much for Fluent as they are for FluentKit. Given the [docs](https://docs.vapor.codes/fluent/overview/) are fall under the Vapor project, they probably are written as Fluent rather than FluentKit. If that doesn't sound right or something doesn't add up I can go back to their Discord and ask a more well-formed question with additional specifics.

---

> You can definitely use [postgres-nio](https://github.com/vapor/postgres-nio) directly though. I'll work on a starter kit that uses this until I can figure out how FluentKit works.

This is a great start! I'll admit that I was asking about Fluent because my SQL tends to be weaker than my Swift, but I'll happily start with this to see what happens. 😄

---

Thank you again for the responses and enthusiasm, this is probably the most fun I've had playing around with a new technology since SwiftUI. 🙂
